### ISSUE TITLE
Dose it support mysql well now?

### ISSUE THREAD

**Issue by dkyaorui** [go-gorm/sharding#16]
## Your Question

I'm using mysql and I‘m not sure if i should try using this library.

![image](https://user-images.githubusercontent.com/29044996/164626937-ee301b80-c704-4410-baaf-7788c035287b.png)
![image](https://user-images.githubusercontent.com/29044996/164627076-aa1df5b6-250a-4fbf-b1f2-baa511f02fd3.png)

**Comment by huacnlee** [comment]
https://github.com/go-gorm/sharding/releases/tag/v0.4.0
