### ISSUE TITLE
db.Statement change after use plugin

### ISSUE THREAD

**Issue by a631807682** [go-gorm/sharding#19]
`stmt.Parse` will change its own value, it will cause some bugs.
https://github.com/go-gorm/gorm/blob/master/migrator/migrator.go#L48
https://github.com/go-gorm/sharding/blob/main/sharding.go#L113
```go
func (s *Sharding) compile() error {
...
			// stmt := &gorm.Statement{DB: s.DB}
			stmt := s.DB.Statement
			if err := stmt.Parse(table); err == nil {
				s.configs[stmt.Table] = s._config
			} else {
				return err
			}
...
}
```

I think the code `stmt := &gorm.Statement{DB: s.DB}` should be used instead, but it is commented, is this necessary?

**Comment by hyperphoton** [comment]
Fixed.
