### ISSUE TITLE
MySQL transaction not work due to conn pool management.

### ISSUE THREAD

**Issue by jiekun** [go-gorm/sharding#41]
## Description
```go
// BeginTx Implement ConnPoolBeginner.BeginTx
func (pool *ConnPool) BeginTx(ctx context.Context, opt *sql.TxOptions) (gorm.ConnPool, error) {
	if basePool, ok := pool.ConnPool.(gorm.ConnPoolBeginner); ok {
		return basePool.BeginTx(ctx, opt)
	}
	return pool, nil
}
```

For this method, when init with default setting, `pool.ConnPool` is actually an `sql.DB` struct, which return `pool, nil` directly. Transaction is not opened.

**Comment by hyperphoton** [comment]
Fixed in [this commit](https://github.com/go-gorm/sharding/commit/bc24a0907a193355179c87b542f00b0c655cd073).
