### ISSUE TITLE
MySQL Nested transaction failed due to incorrect interface impl.

### ISSUE THREAD

**Issue by jiekun** [go-gorm/sharding#43]
## Description
in `gorm.io/gorm/finisher_api.go:547` `Transaction`, nested transaction need to check if connPool fit TxCommitter:
- can fit: in nested transaction now, `BEGIN` has been called, so use `SAVEPOINT` instead
- can't fit: not in nested transaction now, call `BEGIN`.

However, `sharding` plugin impl `BeginTx` / `Commit` / `Rollback` in same `struct`. So it can fit `TxCommitter` interface without `BEGIN` call. The nested transaction won't work.

`ConnPool` struct CANNOT impl `TxBeginner` and `TxCommitter` interface in the same time. When `BeginTx` is called, different struct need to be returned.

**Comment by hyperphoton** [comment]
Fixed in [this commit](https://github.com/go-gorm/sharding/commit/bc24a0907a193355179c87b542f00b0c655cd073).

**Comment by jiekun** [comment]
> Fixed in [this commit](https://github.com/go-gorm/sharding/commit/bc24a0907a193355179c87b542f00b0c655cd073).
I have a PR before. https://github.com/go-gorm/sharding/pull/42/files

Not sure if it could be fixed easily like https://github.com/go-gorm/sharding/commit/bc24a0907a193355179c87b542f00b0c655cd073 .

As far as I remember ConnPool needs to implement another interface (or we need another structure to implement it).

@hyperphoton @jinzhu I strongly suggest to review if the problem can be solve like this.

**Comment by hyperphoton** [comment]
Thank you. @jiekun  
I will review this later.
