### ISSUE TITLE
sharding  Error 1054: Unknown column 'ny_order.deleted_at' in 'where clause'

### ISSUE THREAD

**Issue by QTTQ** [go-gorm/sharding#49]

**Comment by QTTQ** [comment]
2022/07/04 19:07:38 Error 1146: Table 'zft.ny_order_12' doesn't exist
[0.503ms] [rows:0] SELECT `trade_no` FROM `ny_order` WHERE `ny` = '12' AND `ny_order`.`deleted_at` IS NULL

报的是这个 正常不是应该 SELECT `trade_no` FROM `ny_order_12` WHERE `ny` = '12' AND `ny_order_12`.`deleted_at` IS NULL  假如 ny_order_12存在的话

**Comment by huacnlee** [comment]
贴一下你的配置信息，看不到分表配置，无法确定问题

**Comment by QTTQ** [comment]
![image](https://user-images.githubusercontent.com/22019544/177292034-f609465a-0540-4678-b481-cb8a63757b0c.png)
我想问一下 查的时候 会默认查 deleted_at is null 的  但是 加上分表后  无论 是ny_order_* 几 都是ny_order.deleted_at IS NULL 我想根据传的 NumberOfShards 数来对应自动 显示 ny_order_*.deleted_at IS NULL  比如 query = db.GormDB.Debug().Unscoped().Model(&dbmodel.NyOrder{}).Select("merchant_trade_no").Where("ny", "2").Find(&nyOrderSc)  应该是执行的 SELECT trade_no_02 FROM ny_order WHERE ny = '02' AND ny_order_02.deleted_at IS NULL 而不是 SELECT trade_no_02 FROM ny_order WHERE ny = '02' AND ny_order.deleted_at IS NULL

**Comment by hyperphoton** [comment]
The problem description is not very clear. 
If there is still a problem, reopen this issue.

**Comment by zishiguo** [comment]
I also met this question.
