### ISSUE TITLE
Error 1136: Column count doesn't match value count at row 2

### ISSUE THREAD

**Issue by Double1996** [go-gorm/sharding#55]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

Error 1136: Column count doesn't match value count at row 2

mysql create with slice

**Comment by zhwei820** [comment]
You can use latest main branch.

`func TestInsertManyWithFillID(t *testing.T) {
	err := db.Create([]Order{{UserID: 100, Product: "Mac"}, {UserID: 100, Product: "Mac Pro"}}).Error
	assert.Equal(t, err, nil)

	expected := `INSERT INTO orders_0 ("user_id", "product", id) VALUES ($1, $2, $sfid), ($3, $4, $sfid) RETURNING "id"`
	lastQuery := middleware.LastQuery()
	assertSfidQueryResult(t, toDialect(expected), lastQuery)
}
`
