### ISSUE TITLE
sharding key or id required, and use operator =

### ISSUE THREAD

**Issue by Tk4s** [go-gorm/sharding#61]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

When i use preload on sharding table,  the return "msg sharding key or id required, and use operator ="

type A struct {
    ID string
    BS []B
}

type B struct {
    ID string
    AID string
}

var aModel A

db.Model(&A{}).Preload("B").Find(&aModel)

**Comment by huacnlee** [comment]
This is not a bug. 

Sharding must have a shard key, and you must present the shard key in every query conditions. If we not providing that, the Sharding implementation can not know which sub table to query.

**Comment by Tk4s** [comment]
Hi, but i see the sql has shardingkey ,  like this:
SELECT * FROM `scan` WHERE `scan`.`sys_group_space_app_id` = '62f3723a238b2add3cdbed71'

the `sys_group_space_app_id` is table `scan` shardingKey.


And i find another problem.   
1:  cannot use hook 
2: cannot use Clauses 

This will cause GORM to insert data into the primary table instead of the sub-table

**Comment by hyperphoton** [comment]
Your primary table is A but there is no sharding key on A.
