### ISSUE TITLE
如何注册不同的shardingkey 分表策略

### ISSUE THREAD

**Issue by Tk4s** [go-gorm/sharding#62]
## Expected answer

Hi,
    目前有需求是注册不同类型的shardingkey 切片表, gorm  (db.Use()) 如果多次使用相同name的插件会被返回已注册.
    请问该如何实现,  谢谢

**Comment by huacnlee** [comment]
描述不够详细，无法解答

**Comment by Tk4s** [comment]
我有多张不同的表, shardingkey 也不一致, 这个时候当db.USE() 其中一个类型shardingkey的时候, 无法再USE第二个sharding 组件.

**Comment by zouguobing** [comment]
sharding.Register func will be get the same plugin name for sharding，so different sharding-key column could not register successfully when invoking db.USE()

**Comment by hyperphoton** [comment]
Not supported now.
Multiple database connections with different sharding rules can be used in this scenario.

**Comment by ppanphper** [comment]
看gorm文档里写的是支持链式注册多shardingkey 分表规则, 怎么现在不支持了。。

**Comment by Vingurzhou** [comment]
那事务怎么办呢

**Comment by Vingurzhou** [comment]
> 目前不支持。 该场景可以使用具有不同分片规则的多个数据库连接。

那事务怎么办呢
