### ISSUE TITLE
是否可以支持注册不同的shardingkey 分表策略

### ISSUE THREAD

**Issue by ppanphper** [go-gorm/sharding#84]
## Describe the feature

sharding.Register func will be get the same plugin name for sharding，so different sharding-key column could not register successfully when invoking db.USE()

## Motivation

The same database has multiple tables with different shardingkey rules

## Related Issues

https://github.com/go-gorm/sharding/issues/62

Is it possible to support setting plugins name to solve the problem of different shardingKey rules for multiple tables in the same database?

**Comment by zishiguo** [comment]
Isn' t supported ?
